import mongoose from "mongoose";

const lineSchema = new mongoose.Schema(
  {
    lineId: String,
    description: String,
    hsn: String,
    quantity: Number,
    taxableValuePaise: Number,
    cgstPaise: { type: Number, default: 0 },
    sgstPaise: { type: Number, default: 0 },
    igstPaise: { type: Number, default: 0 },
    cessPaise: { type: Number, default: 0 }
  },
  { _id: false }
);

// An invoice the ERP issued for a Rafttaar order (only possible when the seller's
// integration has invoiceSource=erp). The PDF is generated by THIS service and
// Rafttaar stores only its https URL, so that URL must stay reachable.
const schema = new mongoose.Schema(
  {
    order: { type: mongoose.Schema.Types.ObjectId, ref: "Order", required: true, index: true },
    rafttaarOrderId: { type: String, required: true, index: true },
    invoiceNumber: { type: String, required: true, unique: true },
    financialYear: { type: String, required: true },
    invoiceDate: { type: Date, required: true },
    placeOfSupply: String,
    sellerGstin: String,
    buyerName: String,
    lines: [lineSchema],
    taxableValuePaise: Number,
    taxPaise: Number,
    grandTotalPaise: Number,
    status: { type: String, enum: ["draft", "active", "voided"], default: "draft" },
    voidReason: String,
    rafttaarInvoiceId: String,
    pdfToken: { type: String, required: true, unique: true } // unguessable path segment of the public PDF URL
  },
  { timestamps: true, versionKey: false }
);

export const Invoice = mongoose.model("Invoice", schema);

const counterSchema = new mongoose.Schema({ _id: String, seq: { type: Number, default: 0 } }, { versionKey: false });
export const Counter = mongoose.model("Counter", counterSchema);
